apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fr98kp6mg-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fr98kp6mg-dotnet-basic-gitops